DROP SCHEMA IF EXISTS data CASCADE;
CREATE SCHEMA data;

DROP TABLE IF EXISTS CountyLookup CASCADE;
DROP TABLE IF EXISTS AreaLookup CASCADE;
DROP TABLE IF EXISTS AreaTypeLookup CASCADE;
DROP TABLE IF EXISTS naicslookup CASCADE;
DROP TABLE IF EXISTS Wages CASCADE;
DROP TABLE IF EXISTS Crime CASCADE;

CREATE TABLE CountyLookup(
	County VARCHAR(64) NOT NULL,
	Agency VARCHAR(128) NOT NULL
	/*PRIMARY KEY(Agency)*/
	/*FOREIGN KEY(County) REFERENCES AreaLookup(County)*/
);


CREATE TABLE AreaLookup(
	Area VARCHAR(64) NOT NULL,
	County VARCHAR(64) NOT NULL UNIQUE
/*	PRIMARY KEY(Area)*/
	/*FOREIGN KEY(County) REFERENCES CountyLookup(County),
	FOREIGN KEY(Area) REFERENCES AreaTypeLookup(Area)*/

);

CREATE TABLE AreaTypeLookup(
	Area VARCHAR(64) NOT NULL,
	AreaType VARCHAR(64) NOT NULL
	/*PRIMARY KEY(Area)*/
	
);

CREATE TABLE NAICSLookup(
	NAICS VARCHAR(10) NOT NULL,
	NAICSTitle VARCHAR(128) NOT NULL,
	PRIMARY KEY(NAICS)
);

CREATE TABLE Wages(
	Area VARCHAR(64) NOT NULL,
	NAICS VARCHAR(10) NOT NULL,
	Year INTEGER NOT NULL,
	numEstablishments VARCHAR(32) NOT NULL,
	avgEmployment VARCHAR(32) NOT NULL,
	totalWage VARCHAR(32) NOT NULL,
	annualAvgSalary VARCHAR(32) NOT NULL
	/*PRIMARY KEY(Area, NAICS, Year)*/
/*	FOREIGN KEY(Area) REFERENCES AreaTypeLookup(Area),
	FOREIGN KEY(NAICS) REFERENCES NAICSLookup(NACIS),
	FOREIGN KEY(Area) REFERENCES AreaLookup(Area)*/
);

CREATE TABLE Crime(
	Agency VARCHAR(128) NOT NULL,
	Year INTEGER NOT NULL,
	MonthsReportedForCrime VARCHAR(32) NOT NULL,
	totalCrimes VARCHAR(32),
	totalViolentCrimes VARCHAR(32),
	murderCrimes VARCHAR(32),
	rapeCrimes VARCHAR(32),
	robberyCrimes VARCHAR(32),
	aggravatedAssaultCrimes VARCHAR(32),
	totalPropertyCrimes VARCHAR(32),
	burgalaryCrimes VARCHAR(32),
	larcenyCrimes VARCHAR(32),
	motorVehicleTheftCrimes VARCHAR(32)
	/*FOREIGN KEY(Agency) REFERENCES CountyLookup(Agency)	*/
);


